### ISSUE TITLE
http.client.IncompleteRead: IncompleteRead(214292 bytes read, 111194 more expected)

### ISSUE THREAD

**Issue by inhahe** [connerlane/degrees-of-wikipedia#1]
OS: Windows 10 
Python: Python37-32

I only tried it once, and it didn't work. =(
Here's the session:

(dow) D:\py\degrees-of-wikipedia-master\degrees-of-wikipedia-master>main.py
Loading cache... Cache loaded in 0.21 seconds.
save cache on shutdown? [y/n]: y
starting page: https://en.wikipedia.org/wiki/Adolf_Hitler
destination page: https://en.wikipedia.org/wiki/Selenium
checking 0 links on level 0
checking 1 links on level 0
Adolf_Hitler
(cached) Adolf_Hitler
checking 0 links on level 0
(cached) Adolf_Hitler -> World War I
(cached) Adolf_Hitler -> Great Depression
(cached) Adolf_Hitler -> Olympic Games
(cached) Adolf_Hitler -> Israel
(cached) Adolf_Hitler -> Islam
(cached) Adolf_Hitler -> Protestantism
(cached) Adolf_Hitler -> liturgy
(cached) Adolf_Hitler -> Harvard University
(cached) Adolf_Hitler -> IMDb
checking 497 links on level 1
Adolf_Hitler -> 20th Century Press Archives
Adolf_Hitler -> Paintings by Adolf Hitler
Adolf_Hitler -> Toothbrush moustache
Adolf_Hitler -> Der Sieg des Glaubens
Adolf_Hitler -> Paula Hitler
Adolf_Hitler -> Klara Pölzl
Adolf_Hitler -> List of books by or about Adolf Hitler
Adolf_Hitler -> Iron Cross First Class
Adolf_Hitler -> Internet Archive
Adolf_Hitler -> List of Adolf Hitler's personal staff
Adolf_Hitler -> List of streets named after Adolf Hitler
Adolf_Hitler -> Julius Schaub
Adolf_Hitler -> German National Library of Economics
Adolf_Hitler -> Geli Raubal
Adolf_Hitler -> cocaine
Adolf_Hitler -> Hitler and Mannerheim recording
Adolf_Hitler -> Karl Wilhelm Krause
Adolf_Hitler -> Leni Riefenstahl
Adolf_Hitler -> ruptured eardrums
Adolf_Hitler -> psychopath
Adolf_Hitler -> Ernst-Günther Schenck
Adolf_Hitler -> cult of personality
Adolf_Hitler -> Triumph des Willens
Adolf_Hitler -> Der Sieg des Glaubens
Adolf_Hitler -> Theodor Morell
Adolf_Hitler -> amphetamine
Adolf_Hitler -> borderline personality disorder
Adolf_Hitler -> Olympia
Adolf_Hitler -> Walter C. Langer
Adolf_Hitler -> syphilis
Adolf_Hitler -> Führermuseum
Adolf_Hitler -> Eastern Bloc
Adolf_Hitler -> John S. Conway
Adolf_Hitler -> anticlerical
Adolf_Hitler -> irritable bowel syndrome
Adolf_Hitler -> skin lesions
Adolf_Hitler -> Karl Mayr
Adolf_Hitler -> opiates
Adolf_Hitler -> Doktor Koster's Antigaspills
Adolf_Hitler -> sacraments
Adolf_Hitler -> Friedrich Meinecke
Adolf_Hitler -> Berghof
Adolf_Hitler -> Hitler followed a vegetarian diet
Adolf_Hitler -> barbiturates
Adolf_Hitler -> NATO
Adolf_Hitler -> European Theatre of World War II
Adolf_Hitler -> Stunde Null
Adolf_Hitler -> tinnitus
Adolf_Hitler -> irregular heartbeat
Adolf_Hitler -> Office of Strategic Services
Adolf_Hitler -> Robert G. L. Waite
Adolf_Hitler -> giant-cell arteritis
Adolf_Hitler -> atropa belladonna
Traceback (most recent call last):
  File "D:\py\degrees-of-wikipedia-master\degrees-of-wikipedia-master\main.py", line 181, in <module>
    result = relate(start_link, dest_link, cache, grow_cache=False)
  File "D:\py\degrees-of-wikipedia-master\degrees-of-wikipedia-master\main.py", line 148, in relate
    links = get_links_from_page(connection[0], connection[1])
  File "D:\py\degrees-of-wikipedia-master\degrees-of-wikipedia-master\main.py", line 43, in get_links_from_page
    soup = BeautifulSoup(connection, "lxml").find(
  File "C:\Users\inhah\Envs\dow\lib\site-packages\bs4\__init__.py", line 245, in __init__
    markup = markup.read()
  File "c:\python37-32\Lib\http\client.py", line 460, in read
    s = self._safe_read(self.length)
  File "c:\python37-32\Lib\http\client.py", line 612, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(214292 bytes read, 111194 more expected)

**Comment by inhahe** [comment]
I just tried it again, and I got a similar error at a different wikipedia page:

(dow) D:\py\degrees-of-wikipedia-master\degrees-of-wikipedia-master>main.py
Loading cache... Cache loaded in 0.12 seconds.
save cache on shutdown? [y/n]: y
starting page: https://en.wikipedia.org/wiki/Adolf_Hitler
destination page: https://en.wikipedia.org/wiki/Selenium
checking 0 links on level 0
checking 1 links on level 0
Adolf_Hitler
(cached) Adolf_Hitler
checking 0 links on level 0
(cached) Adolf_Hitler -> World War I
(cached) Adolf_Hitler -> Great Depression
(cached) Adolf_Hitler -> Olympic Games
(cached) Adolf_Hitler -> Israel
(cached) Adolf_Hitler -> Islam
(cached) Adolf_Hitler -> Protestantism
(cached) Adolf_Hitler -> liturgy
(cached) Adolf_Hitler -> Harvard University
(cached) Adolf_Hitler -> IMDb
checking 497 links on level 1
Adolf_Hitler -> 20th Century Press Archives
Adolf_Hitler -> Toothbrush moustache
Adolf_Hitler -> Paintings by Adolf Hitler
Adolf_Hitler -> List of books by or about Adolf Hitler
Adolf_Hitler -> Internet Archive
Adolf_Hitler -> Karl Mayr
Adolf_Hitler -> Der Sieg des Glaubens
Adolf_Hitler -> Führermuseum
Adolf_Hitler -> Leni Riefenstahl
Adolf_Hitler -> Paula Hitler
Adolf_Hitler -> Ernst-Günther Schenck
Adolf_Hitler -> Hitler and Mannerheim recording
Adolf_Hitler -> Theodor Morell
Adolf_Hitler -> cocaine
Adolf_Hitler -> barbiturates
Adolf_Hitler -> atropa belladonna
Adolf_Hitler -> Triumph des Willens
Adolf_Hitler -> giant-cell arteritis
Adolf_Hitler -> borderline personality disorder
Adolf_Hitler -> Der Sieg des Glaubens
Adolf_Hitler -> Karl Wilhelm Krause
Adolf_Hitler -> Hitler followed a vegetarian diet
Adolf_Hitler -> syphilis
Adolf_Hitler -> Office of Strategic Services
Adolf_Hitler -> skin lesions
Adolf_Hitler -> sacraments
Adolf_Hitler -> Sebastian Haffner
Adolf_Hitler -> NATO
Adolf_Hitler -> Walter C. Langer
Adolf_Hitler -> Friedrich Meinecke
Adolf_Hitler -> evil
Adolf_Hitler -> irregular heartbeat
Adolf_Hitler -> Hugh Trevor-Roper
Adolf_Hitler -> Aktion T4
Adolf_Hitler -> His cabinet
Adolf_Hitler -> Iron Cross First Class
Adolf_Hitler -> euthanasia
Adolf_Hitler -> John Toland
Adolf_Hitler -> Jehovah's Witnesses
Adolf_Hitler -> enslavement
Adolf_Hitler -> Klara Pölzl
Adolf_Hitler -> Stunde Null
Adolf_Hitler -> potassium bromide
Adolf_Hitler -> opiates
Adolf_Hitler -> cult of personality
Adolf_Hitler -> Berghof
Adolf_Hitler -> Western Bloc
Adolf_Hitler -> Mass
Adolf_Hitler -> European Theatre of World War II
Adolf_Hitler -> amphetamine
Adolf_Hitler -> German National Library of Economics
Adolf_Hitler -> List of streets named after Adolf Hitler
Adolf_Hitler -> Julius Schaub
Adolf_Hitler -> Robert G. L. Waite
Adolf_Hitler -> Holocaust denial
Traceback (most recent call last):
  File "D:\py\degrees-of-wikipedia-master\degrees-of-wikipedia-master\main.py", line 181, in <module>
    result = relate(start_link, dest_link, cache, grow_cache=False)
  File "D:\py\degrees-of-wikipedia-master\degrees-of-wikipedia-master\main.py", line 148, in relate
    links = get_links_from_page(connection[0], connection[1])
  File "D:\py\degrees-of-wikipedia-master\degrees-of-wikipedia-master\main.py", line 43, in get_links_from_page
    soup = BeautifulSoup(connection, "lxml").find(
  File "C:\Users\inhah\Envs\dow\lib\site-packages\bs4\__init__.py", line 245, in __init__
    markup = markup.read()
  File "c:\python37-32\Lib\http\client.py", line 460, in read
    s = self._safe_read(self.length)
  File "c:\python37-32\Lib\http\client.py", line 612, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(212992 bytes read, 471881 more expected)

**Comment by seltzerfish** [comment]
Hey @inhahe ! Thanks for your feedback. 
I've encountered this error myself. I think that this might be an issue involving links that include unicode in the url. However, it could also just be a server or internet error while trying to read a page. I'll look into it some more 👍
